### ISSUE TITLE
Enhancements and Suggestions for Laser Function Plugin

### ISSUE THREAD

**Issue by fredjoe7** [drbap/laser-beam-for-obsidian#1]
Thank you for this plugin.. this is what i wanted out of the laser function from the beginning (follow mouse) 

there is some suggestions, 

1. It seems slightly less smooth. I believe it's a trade-off between smoothness and speed. I feel that prioritizing smoothness would result in more comfortable reading compared to quickness, which can sometimes come across as stuttering.

![demo](https://github.com/drbap/laser-beam-for-obsidian/assets/107930196/9d186d2c-75cf-4a32-ba70-e3c74790daa9)

(i feel it looks smoother in gif than in reality) 

2. how about  an autoscroll function.. like how the mysnippets plugin scrolls as shown below...

Edits: ok we can still use mouse middle click and scroll easily ... (so autoscroll wont be a problem i guess)

![demo1](https://github.com/drbap/laser-beam-for-obsidian/assets/107930196/ee467523-3e08-45cb-8be7-f461841b2f0e)

i dont know if its my computer . it feels very laggy sometimes...
but i can notice its more laggy after i enabled the plugin.

![demo2](https://github.com/drbap/laser-beam-for-obsidian/assets/107930196/f0a468bf-f31a-41cc-b546-c54f77865a57)

**Comment by drbap** [comment]
Thanks for trying it and suggestions. Much appreciated.

Here's how it works for me (8GB Core i5 computer, so it is an old computer). I recorded at 24fps. **Of course I'm exaggerating** the movements just to show that I have no noticeable delays.

![laser_beam_plugin_test](https://github.com/drbap/laser-beam-for-obsidian/assets/70039037/5ddf03c8-d348-4713-b302-aec2e29950c5)

![laser_beam_plugin_test2](https://github.com/drbap/laser-beam-for-obsidian/assets/70039037/367d800e-59ed-454b-95ce-eb12546cf911)

I added a throttle function with a 100 ms delay to avoid consuming too many computer resources to reposition the laser line. What is your screen resolution? I tested the performance (dev tools) and I'm getting 48-52fps (when the plugin laser is activated and moved at that speed).

Well it is version 1.0.0, I hope to keep improving it. This test was recorded using only 2 plugins activated (Style Settings and Laser beam).

**Comment by drbap** [comment]
Here it is in slow mouse movement (I'm also using a screen recording, so it's not the best performance scenario).

![laser_beam_plugin_test3_slow](https://github.com/drbap/laser-beam-for-obsidian/assets/70039037/d18f2758-acd4-4084-b986-33976052229b)

**Comment by drbap** [comment]
I will post an update in a few hours (maybe in a day), so hopefully the performance will be better. Stay tuned.

EDIT: Please let me know if you are using any CSS snippet with animations or a big number of CSS snippets loaded. Anyway, I hope you will notice a performance improvement in your computer.

**Comment by drbap** [comment]
Please check **plugin version 1.0.1**. Let me know if you notice any improvement.

**Comment by fredjoe7** [comment]
I had 50 plugins on..

When i turned them all off, the speed is very much like you have shown in the video...

Even with all them off.. its not that buttery smooth yet even after the update ... smooth like the moving clouds lol..

**Comment by drbap** [comment]
Please check **plugin version 1.0.2**. Let me know if it is working well.

All the  best

**Comment by drbap** [comment]
Here it is how it moves now (v1.0.2) - > 50fps.

![laser_beam_plugin_test_t1](https://github.com/drbap/laser-beam-for-obsidian/assets/70039037/c46f3a44-e09f-4ccc-b00f-9642b5d81b43)

**Comment by fredjoe7** [comment]
Much better experience now... thank you

**Comment by drbap** [comment]
Thank you for testing and for your valuable feedback. Much appreciated. The autoscroll feature, you already said the solution (middle click and move). Maybe in the future I can add the autoscroll function to this plugin (I added it to the list of features to consider).

If you notice other issues, please let me know (open another issue).

All the best
