### ISSUE TITLE
FR: Add support writing mode.

### ISSUE THREAD

**Issue by YIRU69** [drbap/laser-beam-for-obsidian#2]
This is an interesting plugin, it seems to follow the mouse mainly for reading. Can it support laser appearance while typing?

**Comment by drbap** [comment]
Welcome. Thank you for stopping by and for your words about the plugin.

You're right, it was designed primarily for reading. The functionality of following the text cursor (caret) is already on the list of items to be implemented in future updates. But I want this plugin to be easy to use and quick to configure (without so many options).

I understand that the follow caret functionality can be useful for many users. I just need to test the functionality more (reduce performance issues). Stay tuned for future updates, it's definitely on my radar to be implemented as soon as possible.

All the best

**Comment by drbap** [comment]
The laser beam plugin is for **reading** (live preview, source and reading modes).

All the best.

**EDIT**: Stay tuned. The next update will have the feature to follow text caret/cursor for **writing**. So you can use it for **reading** and **writing**. I hope you and others enjoy the new version (I will upload it soon).

**Comment by drbap** [comment]
The next version of laser beam will be able to follow the text cursor (for editing/writing). It was already implemented, still have to test a bit more before uploading the new version.

All the best

**Comment by drbap** [comment]
The next version of laser beam will be able to follow the text cursor (for editing/writing). It was already implemented, still have to test a bit more before uploading the new version.

All the best

**Comment by YIRU69** [comment]
Good news.

**Comment by drbap** [comment]
Please check **plugin version 2.1.1**. Laser will follow the text cursor/caret. You can also use static laser position.

I hope you enjoy.

All the best

**Comment by YIRU69** [comment]
It soooo great for my work. Thanks!
