### ISSUE TITLE
compatibility with magicuser concentration mode

### ISSUE THREAD

**Issue by fredjoe7** [drbap/laser-beam-for-obsidian#3]
![demo54632132232sdsd](https://github.com/drbap/laser-beam-for-obsidian/assets/107930196/3f8a4a48-a93e-4eb9-a19f-68180305cbbc)

the laser goes above the mouse cursor when concentration mode or distraction free mode is toggled on in magicuser theme

**Comment by drbap** [comment]
Thanks for letting me know. I will fix this soon.

All the best

**Comment by drbap** [comment]
Please check **plugin version 2.0.0**. I tested in all window modes as well (Obsidian frame, native frame etc). It works on distraction-free mode and total concentration mode. I had to change how the laser is rendered to get the proper position (regardless of the mode of interface).

You can control laser left and right margins.

Please let me know if it is working well.

All the best

**Comment by drbap** [comment]
Please download the .css because it was using the older version. Re-download the plugin and reload it. It should be working ok now (all modes) and smoother experience. Please let me know.

All the best
