### ISSUE TITLE
Can not be used with the surfing plug-in

### ISSUE THREAD

**Issue by desire-achieve-obtain** [drbap/laser-beam-for-obsidian#4]
When the mouse moves over a surfing page, the laser beam does not follow the movement.

**Comment by drbap** [comment]
Thank you for your feedback on the **laser beam plugin** and its interaction with the surfing plugin. I appreciate you letting me know about this compatibility issue.

The vast number of plugins available for Obsidian (over 1700) presents a significant challenge in ensuring perfect compatibility across all of them. While I strive to address compatibility issues whenever possible, I currently don't have the time to prioritize a fix for the specific interaction with the surfing plugin. However, your feedback is valuable and will be taken into consideration for future development.

While I can't address this right away, I'll keep this on my radar for future updates. In the meantime, managing potential conflicts by enabling or disabling plugins based on your current task is the proper strategy.
